[package]
name = "aaah"
version = "1.0.0"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
publish = false

[[bin]]
name="aaah"
path="src/main.rs"

[profile.release]
panic = 'unwind'
incremental = false
overflow-checks = true
